name: Docs deploy

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm ci
      - name: build docs
        run: npm run docs
      - name: zipping docs
        run: zip -r docs.zip docs
      - name: Copy docs to Toolforge
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/mwn/mwn/docs.zip
          remote: /data/project/mwn/docs.zip
          host: login.toolforge.org
          username: ${{ secrets.TOOLFORGE_USERNAME }}
          privateKey: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}
          rmRemote: true
      - name: unzip
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /data/project/mwn && rm -rf docs && unzip docs.zip && rm -rf public_html/docs && rm -rf www/static/docs && cp -r docs public_html && cp -r docs www/static
          host: login.toolforge.org
          username: ${{ secrets.TOOLFORGE_USERNAME }}
          privateKey: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}
